site_name: goulash
theme_dir: glsh
repo_url: https://github.com/mattvonrocketstein/goulash.git
site_author: mvr
markdown_extensions: [markdown.extensions.footnotes]
pages:
- 'Home': 'index.md'
- 'Commands': 'usage.md'
- 'Library Usage': 'library.md'
- 'API Reference': 'API.md'
