site_name: goulash
theme: bootstrap
repo_url: https://github.com/mattvonrocketstein/goulash.git
site_author: mvr
pages:
- 'Home': 'index.md'
- 'Commands': 'commands.md'
- 'Decorators': 'decorators.md'
- 'API Reference': 'api/index.html'
